.rubocop.yml:
  default_configs:
    Lint/Void:
      Enabled: false
Gemfile:
  optional:
    ":system_tests":
      - gem: voxpupuli-acceptance

appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.github/workflows/release.yml:
  unmanaged: false
.github/workflows/release_prep.yml:
  unmanaged: false
.gitlab-ci.yml:
  delete: true
